### ISSUE TITLE
ArduinoOPL2 and Teensy

### ISSUE THREAD

**Issue by KasperSimonsen87** [DhrBaksteen/ArduinoOPL2#57]
Hi there

On https://github.com/DhrBaksteen/ArduinoOPL2/wiki/Connecting you specify that you can use Teensy LC, 3.0 and later. 

I was wondering however how that is possible since according to https://www.pjrc.com/teensy/techspecs.html the 3.0 and later only output 3.3V, and not the 5V required by the board?

Best regards,
Kasper

**Comment by DhrBaksteen** [comment]
Hi.

When you connect the Teensy by USB the VIN pin will pass the 5v from the USB. You can use this to feed the OPL2 board. You could also power both the Teensy and the OPL2 board from an external 5v supply through this pin.

The 3.3v logic not an issue, the ICs of the OPL2 board support this and you don't have to worry about frying the Teensy because the OPL2 board does not output any signal.

Cheers,
Maarten
